version: "2"
services:

  mysql:
    image: mysql:5.6
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: toor
        MYSQL_PORT: 3306
    ports:
      - 3306:3306
    volumes:
        #  - ./runenv/mysql:/etc/mysql
      - $PWD/init.sql:/docker-entrypoint-initdb.d/grant.sql
    container_name: mysql

  simplescoreserver:
    image: golang:1.13-alpine3.10
    ports:
      - 9090:9090
    volumes:
      - $PWD:/simplescoreserver
    working_dir: /simplescoreserver
    #command: sh -c "apk add git mysql-client && go get github.com/go-sql-driver/mysql && go get golang.org/x/xerrors && go build -o vulnapp && ./vulnapp -p 9090"
    depends_on:
      - mysql
    container_name: simplescoreserver
    tty: true

